### ISSUE TITLE
Feature: add support for all barcode types supported by zxing library

### ISSUE THREAD

**Issue by ioangogo** [brarcher/loyalty-card-locker#10]
For example a KFC card is required to be scanned and having this app remake the barcode could be better

**Comment by brarcher** [comment]
I am not clear on the request. What does it mean to generate a new barcode? The actual barcode image is not saved by the app; instead the barcode number and type is saved. When an store entry is selected the barcode is generated on demand and displayed.

If you could give a step by step use case for the request, it would help my understanding of what you are after. Thanks!

**Comment by ioangogo** [comment]
Ah, Apologies, I have just scanned a card with a elan style barcode and it worked, i cant seem to scan the card I thought it was that uses a PDF417

**Comment by brarcher** [comment]
@ioangogo Currently the zxing library, used to scan and generate barcodes, supports the following 1D barcodes and is configured in this application to do so:

- UPC_A
- UPC_E
- EAN_8
- EAN_13
- CODE_39
- CODE_93
- CODE_128
- ITF
- RSS_14
- RSS_EXPANDED

Have you observed a barcode for a loyalty card which is a 2D barcode, such as PDF417? If so, 2D barcode support can be enabled easily, I believe. Let me know, and I can do so and release another version of this application with 2D barcode support.

**Comment by ioangogo** [comment]
Yes, The loyalty card that i have seen  with a 2D barcode is a KFC card with the PDF417 and subway with a data matrix

**Comment by brarcher** [comment]
Although the zxing library is capable of scanning multiple types of barcodes, it appears it is only currently able to generate the following:

- EAN_8
- EAN_13
- UPC_A
- QR_CODE
- CODE_39
- CODE_128
- ITF
- PDF_417
- CODABAR
- DATA_MATRIX
- AZTEC

The only missing barcode type which Stocard supports is GS1_128. That is, this application will not be able to support GS1_128 barcodes whereas Stocard will be able to.

I'l see about adding support for only the barcode types I've listed above.

**Comment by brarcher** [comment]
[This pull request](https://github.com/brarcher/loyalty-card-locker/pull/13) adds support for all barcodes that zxing can generate. The next release should take care of this.

**Comment by brarcher** [comment]
A release has been cut, and should be picked up by F-Droid in the next day or so.
