### ISSUE TITLE
Cannot scan barcodes on an Acer Iconia One 8

### ISSUE THREAD

**Issue by Zero3K** [brarcher/loyalty-card-locker#105]
I tried putting one of them in clear view of the back camera and it still didn't pick it up. They are small cards with the barcode on them. One was the Membership Card for Baptist East Milestone Wellness & Fitness Center and the other is a Rewards Card for The Vitamin Shoppe.

**Comment by Zero3K** [comment]
I have just tried scanning the GameSpot PowerUp Rewards card and two Best Buy Gift Cards with no luck.

**Comment by brarcher** [comment]
Hm, sorry that the app is not working for you. When it is attempting to scan, does the screen display a blinking red line and say at the bottom "Scan Card's Barcode"? If so, could you try installing the following application and see if it is able to scan the barcode?

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

That application uses the same library I use, and I believe it is from the same developers. Let me know if that is successful or not, as that will help determine what is not working.

**Comment by Zero3K** [comment]
1. Yes, the  blinking red line and "Scan Card's Barcode" are displaying.
2. That app is not able to scan the barcode of a 3DS game.

Maybe offering the option of using the front camera will help.

**Comment by brarcher** [comment]
I think that if the Barcode Scanner app is failing, then this application would also fail, as both use the same underlying library. I would encourage you to log an issue against the creators of the library. On Google Play the developers of the Barcode Scanner app mention the following:

> If your device is not scanning, first try workarounds for device bugs in Settings. Enable all of them, and then try disabling one at a time to determine which is necessary. If this does not help, try clearing the device cache and settings from Android settings.
> 
> If these still do not work and you believe there is an app problem, send a message with the following information. Messages without this information can't be acted on, so are ignored.
> 
> - Device type
> - A basic description of what does not work: crashes? does not scan? looks strange?
> - Acknowledgement that you tried the steps above first
> - A device log capture from when it starts

**Comment by brarcher** [comment]
If after contacting the writers of the scanner app it is found that there issue is with the Loyalty Card Keychain app which needs to be resolved, please re-open this issue. Otherwise, I'll assume that there is a bug in the zxing library which needs to be resolved. The recent release of this app did update the version of the zxing library used, in case that has a positive affect.
