### ISSUE TITLE
German translation.

### ISSUE THREAD

**Issue by z3ttacht** [brarcher/loyalty-card-locker#11]
I've long waited to be able to recommend an alternative to Stocard to family and friends.
Therefore I would like to help with translating loyalty-card-locker to German.
Do I only need to copy `app/src/main/res/values/strings.xml` to `app/src/main/res/values-ge/strings.xml` and start translating?

**Comment by brarcher** [comment]
> I've long waited to be able to recommend an alternative to Stocard to family and friends.
> Therefore I would like to help with translating loyalty-card-locker to German.

Thanks for the interest in the project.

According to [this documentation](http://developer.android.com/reference/java/util/Locale.html), the language code for German is "de". Likely the name of the values directory would then be: "values-de".

And, if you simply copy "strings.xml" into "values-de" and edit it with appropriate translations, you will be good to go. If in the future additional strings are added and need translating into German, may I ping you to help out?

**Comment by z3ttacht** [comment]
> According to this documentation, the language code for German is "de". Likely the name of the values directory would then be: "values-de".

Got it. Thanks for the pointer.

> And, if you simply copy "strings.xml" into "values-de" and edit it with appropriate translations, you will be good to go.

Great. Thanks for the information.
I'm off to fork and gonna issue a pull request afterwards.

>  If in the future additional strings are added and need translating into German, may I ping you to help out?

Of course. Ping away!

**Comment by z3ttacht** [comment]
@brarcher So now I have finished the first version of the translation to German.

But before issuing a pull request, I would like to compile the app myself. For testing, especially regarding length of strings.
Since I'm new to app development, how would I manage to do that. Does executing `gradle build lint test` on my local machine suffice. Or would I be better off synchronizing my repository with [TravisCI](https://travis-ci.org/brarcher/loyalty-card-locker) as well.

**Comment by brarcher** [comment]
The command
```
gradle build lint test
```
will compile the application, make sure that there are no obvious mistakes or style concerns (lint) and run the unit tests. It probably assumes that android SDK is in your path somewhere. You will then need to install the application. I think that it will put the generated file here:
```
app/build/outputs/apk/app-debug.apk
```
You will need to uninstall your copy of the application first from F-Droid before installing your built copy.

Good luck! If you run into anything, let me know.

**Comment by SecUpwN** [comment]
Thanks for filing thisIssue @z3ttacht! Let me know if you need any help. Grüße aus der Heimat. ;-)

**Comment by brarcher** [comment]
@z3ttacht were you able to get the project building locally with the translations? I've added some instructions to the README.md file demonstrating how one may build the project, if it is helpful.

**Comment by brarcher** [comment]
As the German translation is now merged in, closing this request.
