### ISSUE TITLE
The new version isn't installing

### ISSUE THREAD

**Issue by Zero3K** [brarcher/loyalty-card-locker#119]
It tells me "app not installed" when trying to update v0.10 to v0.11. I am running v5.1 of Android.

**Comment by brarcher** [comment]
Hm. Where are you getting the app from? The Google Play Store, F-Droid, or compiling from source?

I see from the Google Play dashboard that 4 users with Android 5.1 were able to successfully upgrade to v0.11. Are you able to capture the logs after you attempt to upgrade? That may help determine what is going wrong.

**Comment by brarcher** [comment]
I've not heard anything back. If you continue to have this issue and are interested in helping get to the bottom of it, please re-open the issue.
