### ISSUE TITLE
6.01 - Crash when accessing camera

### ISSUE THREAD

**Issue by davidium** [brarcher/loyalty-card-locker#12]
The app must be given permission to use the camera in Settings -> Apps -> Loyalty Card -> Permissions. If not the app crashes when scanning in a new card via camera. 

I wasn't sure if this was by design, but I wanted to report it for others.

**Comment by brarcher** [comment]
@davidium Do you happen to know if this occurs in release v0.2? Initially I neglected to add the permission, but it was added in release v0.2.

**Comment by davidium** [comment]
Yes version 0.2. I believe the permission has been added, as I was able to
enable it. Before I manually enabled the camera permission however, the app
would crash when it tried to use the camera. I think it had trouble
prompting the user for camera access, which is new in android 6.0.

Perhaps you would be able to have the app prompt this when the user opens
the locker for the first time?

I hope this is helpful, let me know if there is anything I can do. Loving
the app so far, and I really appreciate the work you put into it.

-David

**Comment by brarcher** [comment]
I've not played with Android 6 thus far, my devices are too old. (:

Are you familiar with how one would prompt for the camera permission in Android 6, and might be interested in proposing a patch? Interestingly, the [library](https://github.com/journeyapps/zxing-android-embedded) which is used to scan the barcode mentions:
```
The camera permission is required for barcode scanning to function. 
It is automatically included as part of the library. On Android 6 it is 
requested at runtime when the barcode scanner is first opened.
```
Perhaps I am missing something in the setup, and the request is not being made...

**Comment by davidium** [comment]
I'm not a developer, so I can't help too much. But,

I did find this android page which looks like it might have the
information. Check under the section "Request permissions you need" to see
if that is of any help.

http://developer.android.com/training/permissions/requesting.html#perm-request

Also, here is "reenactment" video of the crash, and what I did to fix it.
At the moment the app crashes, usually the app would request permission to
use a service. This is a new feature in android 6.0.

https://youtu.be/_CH76xdVv1w

It's almost a non issue, since there is an easy fix under settings, but I
wanted to make you aware anyway. :)

Hope this is helpful,

David

I've not played with Android 6 thus far, my devices are too old. (:

Are you familiar with how one would prompt for the camera permission in
Android 6, and might be interested in proposing a patch? Interestingly, the
library <https://github.com/journeyapps/zxing-android-embedded> which is
used to scan the barcode mentions:

The camera permission is required for barcode scanning to function.
It is automatically included as part of the library. On Android 6 it is
requested at runtime when the barcode scanner is first opened.

Perhaps I am missing something in the setup, and the request is not being
made...

—
Reply to this email directly or view it on GitHub
<https://github.com/brarcher/loyalty-card-locker/issues/12#issuecomment-182678565>
.

**Comment by brarcher** [comment]
I think the issue may have been a bug in the [zxing-android-embedded](https://github.com/journeyapps/zxing-android-embedded) library which was being used. A recent release  mentions [this fix](https://github.com/journeyapps/zxing-android-embedded/pull/123) for Android 6 permission support. This application is now updated to use the latest revision of zxing-android-embedded, so maybe this issue is now resolved.

When the next release is pushed to F-Droid, please take a look and see if the issue persists.

**Comment by brarcher** [comment]
A release has been cut, and should be picked up by F-Droid in the next day or so.

**Comment by davidium** [comment]
The fix works and functions as expected. Awesome job
