### ISSUE TITLE
Show the presentation only once

### ISSUE THREAD

**Issue by arno-github** [brarcher/loyalty-card-locker#131]
Each time I open the app, I get the presentation, even if I look the presentation till the last screen.

**Comment by brarcher** [comment]
Interesting. When the application loads it will check if the SharedPreferences setting "firstrun" exists. If it does not exist it will set it to 'false' then run with first load wizard. On my test devices (android 6 and 4.4.2) the wizard only appears when the app has been reset. If the wizard is being loaded each time then this must mean it is unable to save any SharedPreferences.

Can you provide any details on your device and the version of Android it is running? Can you also provide the logs from when you launch the application?

**Comment by arno-github** [comment]
LG-D855 with CyanogenMod 14.1-20161215-NIGHTLY-d855 (yes, it's an old one I have to update to lineage ;-)).
Is this one enough?
https://framabin.org/?47386a6d40e06614#dzTVC/Kel+BySkOipO3+dX91Hv4/zNks+7kqFDpz10E=

**Comment by brarcher** [comment]
Looking at the logs it appears that the application is having permission issues, and thus is not able to write to its private internal storage space:

> 07-23 11:14:13.060 E/SharedPreferencesImpl( 2104): Couldn't create directory for SharedPreferences file /data/user/0/protect.card_locker/shared_prefs/protect.card_locker.xml
> 07-23 11:14:13.066 W/FileUtils( 2104): Failed to chmod(/data/user/0/protect.card_locker/databases/LoyaltyCards.db): android.system.ErrnoException: chmod failed: EPERM (Operation not permitted)

From this I would expect that any cards which were created would not persist if the application were closed down or if the phone were rebooted. Have you observed this?

I wonder if you could resolve the issues by uninstalling and reinstalling the application. That may delete the underlying data then attempt to recreate them again.

**Comment by arno-github** [comment]
No, I saved a lot of cards and they are still there after a reboot :-)
I deinstall/reinstall and import my data, and it doesn't show again the presentation :-)
Thanks!
