### ISSUE TITLE
Allow custom colors for card listings

### ISSUE THREAD

**Issue by brarcher** [brarcher/loyalty-card-locker#136]
(Request submitted from Google Play user).

Allow each card to have a custom color, which is displayed on the main screen. This is similar to how Clear List works:

![image](https://user-images.githubusercontent.com/5264535/28746507-ac347d3e-745b-11e7-8446-9d589aad6f59.png)

Except that the colors should not be preset options but are selectable from a wheel:

![image](https://user-images.githubusercontent.com/5264535/28746511-c1cbd750-745b-11e7-8f63-b54b33594cae.png)

**Comment by FireMotion** [comment]
Agreed, with the colors it's easier to find the card you need, plus it makes the app look better (given the design is updated to fit colors better, i.e. appropriate padding/margins, font size/weights). 

I'd even settle for a bare bones version:
Text inputs for the hexadecimal color code for font color and background color. Or one that's hidden from the UI, but usable through the file import.

**Comment by brarcher** [comment]
I've a prototype of something similar to this feature posted here if you would like to take a look:
https://github.com/brarcher/loyalty-card-locker/issues/86#issuecomment-364762869

**Comment by brarcher** [comment]
The next release will have the ability to specify the color used for the icon on the card list page, as well as the colors used for the store name and background on the single card view page. That should satisfy this request. If not, please re-open.
