### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by beng7** [brarcher/loyalty-card-locker#139]
Hi Brarcher
love your app - keep it simple and private
I can see you need help with interface; not too much of a grphic designer myself but I can help with French translation if you want...
Thanks

**Comment by beng7** [comment]
duh - please ignore will have a go by myself as explained in readme

**Comment by brarcher** [comment]
I've accepted your request on Transifex, thanks!

If you would like to help out with the user interface, take a look at the following issues for discussions:
https://github.com/brarcher/loyalty-card-locker/issues/123
https://github.com/brarcher/loyalty-card-locker/issues/88

**Comment by beng7** [comment]
Thanks - sorry forgot to reply
dealt with the outstanding french translations
I am sorry I am not developer, I can basic graphics but I do not feel I could help you with these 2 issues
BTW, I'm happy with the interface at the moment plain and simple.
Thanks a lot

**Comment by PanderMusubi** [comment]
Please set a title at Transifex. The translations for loyalty-card-locker are now labeled under `N/A`. That could be changed to `Loyalty Card Locker` e.g.
