### ISSUE TITLE
Move barcode closer to top/bottom of screen

### ISSUE THREAD

**Issue by dbolton** [brarcher/loyalty-card-locker#143]
I would like to scan my library card at a self-checkout station. The laser is within an indentation in the side of the checkout station. 

With the current layout the 1D barcode is quite far from both top and bottom of the screen so the laser doesn't reach the barcode. 

I read a discussion in another issue about making the barcode full screen when you tap on it. That would be helpful for my use case. 

I realise my use case is unusual and understand if it is not something you want to support.

**Comment by az0** [comment]
I have the same problem at my library, so I cannot scan the barcode on this app

**Comment by devurandom** [comment]
I also use the app for storing the code on a membership / ID card and have the same issue with our time tracking station.

**Comment by clach04** [comment]
Same issue at my library. Work around is to screenshot and then crop it. Move to top of screen and resize in gallery.

**Comment by clach04** [comment]
Being able to position the barcode, possibly along with #231, and #262 might help with this.

**Comment by TheLastProject** [comment]
I am a bit confused at what you people mean. It's like, the scanned only allows you to insert the phone very slightly, so it doesn't reach down the screen far enough to scan the barcode? Could anyone maybe take a picture of the scanner at the library so I could understand the issue better? I've been tackling a lot of the (minor) issues in this project lately so it'd be nice to understand this better so I can try to make sure I get it right.

**Comment by clach04** [comment]
Correct.

I suspect a good way to demo this would be either a picture of a phone in one of these devices or phone and card side by side showing placement of barcode.

I have a pic of a scanner:

![image](https://user-images.githubusercontent.com/424032/72672457-3ec15700-3a0f-11ea-9775-a21364eecbbe.png)


I will upload and try and sort side-by-side another day unless some one beats me to it.

**Comment by TheLastProject** [comment]
Please take a look at #348 and, if you are able to compile the app yourself, please give the branch a try and confirm if it solved the problem for you.

**Comment by clach04** [comment]
@TheLastProject looking at description/screenshots for #348 looks like that would resolve this. I don;t have way to build. Do you happen to have an APK you could upload to your release page https://github.com/TheLastProject/loyalty-card-locker/releases ? I'd be happy to test (NOTE library closed until Tuesday due to bank holiday so real-world-in-the-wild test will take a few days).

**Comment by TheLastProject** [comment]
Here's a .apk of commit 3600065ef8fde538dd994b8ab26b50dbc21c2006:
[app-debug.zip](https://github.com/brarcher/loyalty-card-locker/files/4083322/app-debug.zip)

No worry about it taking a few days. @brarcher is generally very busy too so it'll definitely take longer than that for the feature to possibly be accepted :)

**Comment by clach04** [comment]
@TheLastProject cool, will try on phone today, library next week.

Probably moot now, but current behavior photo compared with card (i.e. not your APK):

![image](https://user-images.githubusercontent.com/424032/72686961-80550f00-3aae-11ea-842c-e44b6fd10da8.png)

Barcodes are the larger box on each.

**Comment by clach04** [comment]
> Here's a .apk of commit [3600065](https://github.com/brarcher/loyalty-card-locker/commit/3600065ef8fde538dd994b8ab26b50dbc21c2006):
> [app-debug.zip](https://github.com/brarcher/loyalty-card-locker/files/4083322/app-debug.zip)
> 
> No worry about it taking a few days. @brarcher is generally very busy too so it'll definitely take longer than that for the feature to possibly be accepted :)

Looks good on my Samsung S9 (running Android 9). I think this will work 👍 - interestingly my device has curved corners (its the one thing I dislike about the S9) so it will be interesting to see how this works for other barcodes, it may benefit from having zooming and scrolling around - but that's an different enhancement request.

Thanks for taking the time to work on this @TheLastProject!

For anyone else trying this out:
* upgrade your existing version
* do an export (older versions didn't have import/export support)
* then uninstall - the debug APK can't be used to upgrade
* then install debug apk

**Comment by brarcher** [comment]
> @brarcher is generally very busy too so it'll definitely take longer than that for the feature to possibly be accepted :)

I appreciate the understanding and patience. (:  

Thanks for the photos @clach04, they were helpful in understanding the use case.

I'll take a look at the PR next.

**Comment by clach04** [comment]
I tested debug build for #348 yesterday in my local library, as expected worked first time 👍

**Comment by brarcher** [comment]
This is now available in v0.37. It should be available now on the Play Store, F-Droid, and on the Releases page.
