### ISSUE TITLE
Add shortcuts from the launcher widget page

### ISSUE THREAD

**Issue by brianmercer** [brarcher/loyalty-card-locker#158]
Sorry, I can't reopen https://github.com/brarcher/loyalty-card-locker/issues/154

The only additional feature would be to be able to add the shortcut thru the widget interface of the Launcher.  Same as for the widget, but for the shortcut. I think it is in the manifest:
https://github.com/connectbot/connectbot/blob/3bbf91a08c5dd8234c442df8c5e1a0319276794a/app/src/main/AndroidManifest.xml#L44

and what this guy is explaining here: https://stackoverflow.com/questions/11439253/add-my-app-to-the-add-shortcut-list-to-have-a-shortcut-on-homescreen

You already had the code for selecting a specific card while setting up the widget.

Thanks again.

**Comment by brarcher** [comment]
Oh, I did not know that one could create a shortcut from the launcher. This way makes much more sense than creating the shortcut from within the app.

I've some changes which will do just this. When creating a widget there would be an option for creating a card shortcut:

<img width="247" alt="screen shot 2017-11-26 at 8 50 26 pm" src="https://user-images.githubusercontent.com/5264535/33247388-bf4f0bd4-d2eb-11e7-9f3f-46d6cb576696.png">

and if selected a screen showing all the available cards would be shown. 

<img width="249" alt="screen shot 2017-11-26 at 8 50 43 pm" src="https://user-images.githubusercontent.com/5264535/33247399-d639229e-d2eb-11e7-9531-6a4314edc75e.png">

Selecting a card would end up with an icon on the home screen that would open that card

<img width="78" alt="screen shot 2017-11-26 at 8 53 50 pm" src="https://user-images.githubusercontent.com/5264535/33247411-eda276c4-d2eb-11e7-99eb-a57abae06391.png">

Does that sounds about right? If so, I'll plan on adding this support and removing the shortcut support I released the other day.  Thanks for the information about shortcuts, as I was not aware of how to do it easily. Instead, I found the hard ways first. (:

**Comment by brianmercer** [comment]
That looks perfect.

Some apps also create shortcuts from within the app. 

You have put in a lot of work. But it really is an excellent app.

**Comment by brarcher** [comment]
In your opinion, should the option to create a shortcut when creating/editing a card be kept (e.g. is it valuable)?

**Comment by brianmercer** [comment]
Yes, I would leave it in.

It is a good reminder that the feature exists. Better than any documentation.

It looks like Google chose the words "Add to home screen" for the menu option in Chrome: https://developer.chrome.com/multidevice/android/installtohomescreen
If Google thinks that is the clearest wording, that may be the way to go.

**Comment by brarcher** [comment]
I agree that Chrome has the better wording. I'll update this app to mach. (https://github.com/brarcher/loyalty-card-locker/pull/161)

Thanks for the feedback. I'll keep the existing option to add shortcuts when adding/editing cards. The ability to add from the launcher will appear in the next version. When that comes out if you have more feedback, please re-open this.
