### ISSUE TITLE
Share my cards with another user

### ISSUE THREAD

**Issue by baruchiro** [brarcher/loyalty-card-locker#159]
I have cards and my wife also has, I have to see my wife's cards so I can use them.

**Comment by brarcher** [comment]
The app has an option to backup and restore cards. This can be found from the main activity by clicking on this menu option:

<img width="34" alt="screen shot 2017-11-27 at 9 12 54 am" src="https://user-images.githubusercontent.com/5264535/33270801-453760b8-d353-11e7-90a1-a5551288c779.png">

You can then export your cards, share the file with someone, and they can import them.

<img width="242" alt="screen shot 2017-11-27 at 9 14 00 am" src="https://user-images.githubusercontent.com/5264535/33270834-5fd165ea-d353-11e7-908b-e898ae2ba222.png">

The data from the app, however, is intended to backup an individual's cards. So, if you have cards added and someone else has other different cards added, you will not be able to share each other's backups and then both have each other's cards.

Does the backup feature meet what you are looking for, or are you aiming for something else? If something else, can you explain how it might work or how you might use it?

**Comment by baruchiro** [comment]
If I add a firebase support? (Server DB)

**Comment by brarcher** [comment]
One of the goals for the project is to not require the network permission, and to not integrate with cloud providers. This is to remove the possibility that the app is sending data about the user to some company. I'm not sure I'm too interested in add support for firebase at this time.

Is there another alternative which may help?

**Comment by baruchiro** [comment]
Without network? Not Really...

**Comment by baruchiro** [comment]
Now I work on add firebase to app.
If you are still interested, maby split to two apps.
I'm new in open source projects, so let's see if I do it correctly.

**Comment by brarcher** [comment]
> If you are still interested, maby split to two apps.

You are welcome to fork this application, modify it, and release it as a new, separate application. There are a few limits on what is possible based on the license used (GPLv3). If you choose to go this path, I would request the following:
- Change the name (e.g. [here](https://github.com/brarcher/loyalty-card-locker/blob/e14da63d06f7f32f33ea5b26d22417022c3d1a83/app/src/main/res/values/strings.xml#L4) and [here](https://github.com/brarcher/loyalty-card-locker/blob/e14da63d06f7f32f33ea5b26d22417022c3d1a83/app/src/main/res/values/strings.xml#L90)), [application ID](applicationId), and [launcher icon](https://github.com/brarcher/loyalty-card-locker/tree/master/app/src/main/res/mipmap-xxxhdpi) of new application so it is not confused with this one.
- Remove my name from the [About dialog](https://github.com/brarcher/loyalty-card-locker/search?utf8=%E2%9C%93&q=Branden&type=) and update the Copyright year to start in 2017 (as you will own the new name).
- The source needs to be available to any user of the application (via the GPLv3).
- The assets used in the application (excluding the launcher icon) were derived from other sources, so as long as you continue to mention them in the [About dialog](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/main/java/protect/card_locker/MainActivity.java#L196) it should be OK to continue using them.
- Any other restrictions that the GPLv3 requires

I've received at least one other request for integrating with cloud providers for backup (such as Google Drive), so there may be an audience for such features. If you have any questions, just let me know.

> Without network? Not Really...

Alternatively, is there a way to share the data from an application and put it into firebase, then retrieve it from firebase and share it with this app? In doing, this app would not need to have network access. Support would need to be added to this app to allow accepting backup data via sharing, and it could be made flexible to allow importing of other user's cards (whereas now it may reject them). This way may avoid forking this application but may require creating a simpler, smaller application.

**Comment by baruchiro** [comment]
First, thank you about explanation of privilages in GPLv3.

I need to check the offline option in firebase. there is one.
And another question- I don't know to write an UnitTest, so right now I delete the units that throw me a code errors, but now I acctualy understend that they are important, because I can use them for check my code without run my new version of app.

so.... learn and write them, or give up?

**Comment by baruchiro** [comment]
And third option is to add FirebaseHelper over the SQLHelper to take all data from SQL and put it in Firebase, but it is more work.

**Comment by brarcher** [comment]
> I need to check the offline option in firebase. there is one.

From the link you provided it sounds like the offline feature is if one is temporarily unable to access the Internet, which may not fit the model of preventing Internet access to the app.

Is there an option to have a second app which access Firebase for Loyalty Card Locker, using data which is shared? Or, would Firebase need to be incorporated into Loyalty Card Locker? Is there an option to have plugins for Loyalty Card Locker and a Firebase plugin is one possibility?

> I don't know to write an UnitTest... so.... learn and write them, or give up?

I've found that the unit tests are valuable in helping me keep the basic functionality of the app working, as well as catching edge cases that I may not be able to test manually. Any new features for the app would need to be accompanied by supporting unit tests, unless doing so is impractical (e.g. Robolectric cannot support it).

**Comment by brarcher** [comment]
If there a way forward with this proposal which does not require the app to have the Internet permission, please re-open with details. Otherwise, at this time, it appears that there is nothing further to do on my side and I'll close this issue.
