### ISSUE TITLE
delete option

### ISSUE THREAD

**Issue by beng7** [brarcher/loyalty-card-locker#178]
Sorry, maybe i missed it but i find myself with a duplicate (card renewal but with a different number), i created the new card :same name but different number and now i have 2 cards by the same name, an old decrepit one + a new one (OK, i realised i should have edited the card!)
The issue is i have no option to delete the old card

**Comment by brarcher** [comment]
If you are able to open the card, you should be able to delete it. The following clip shows an example: 

![out](https://user-images.githubusercontent.com/5264535/35080334-d37a7702-fbda-11e7-8dd9-80d5ee0ded46.gif)

Does this help in finding the delete option? Or, is something going wrong and you are unable to reach the delete option?

**Comment by beng7** [comment]
hi 
DUH!!!!!!! 
(i guess it was late in the evening) 
Thanks a lot for your quick answer! 
cheers 
ben 


----- Original Message -----
