### ISSUE TITLE
New releases don't install

### ISSUE THREAD

**Issue by surferjoeit** [brarcher/loyalty-card-locker#183]
Hello,
first of all thanks for this great app.
Unfortunately i have this problem with latest release. If i try to update with F-Droid, it forces F-droid to close and don’t install.
In addition, i manually downloaded the apk file from github but when i try to access the download folder in order to install it, file manager suddenly closes. I have to manually remove the apk file by connecting device to PC and using PC file manager to be able to access device download folder.
I had the same problem with other apps and it was related to a bug with android build tools:
https://issuetracker.google.com/issues/64434571
For other apps it has then been solved by changing build tools to 27.0.1.
I'm not a developer so i can't help you more than this.. sorry.
Android 5.0.2.

Thanks a lot

**Comment by brarcher** [comment]
Thanks for the bug report and the link. Researching it further, the root issue is a bug in Android which is exposed by recent build tool changes.

Currently I am using build tools 26.0.2. The Google issue tracker says that 27.0.1 has the workaround. I'll update to the latest and rebuild.

**Comment by surferjoeit** [comment]
Many thanks.

**Comment by brarcher** [comment]
Can you try this apk out and see if it installs? I've updated the build-tools used locally and changed the version number, besides that there are no other changes from the latest release.

[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1656669/app-release.apk.zip)

**Comment by surferjoeit** [comment]
Same issue. Ad soon as i unzip the file the file manager closes.

Il 23 gennaio 2018 17:10:09 CET, Branden Archer <notifications@github.com> ha scritto:
>Can you try this apk out and see if it installs? I've updated the
>build-tools used locally and changed the version number, besides that
>there are no other changes from the latest release.
>
>[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1656669/app-release.apk.zip)
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/loyalty-card-locker/issues/183#issuecomment-359840789

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by surferjoeit** [comment]
Same issue. Ad soon as i unzip the file the file manager closes.

Il 23 gennaio 2018 17:10:09 CET, Branden Archer <notifications@github.com> ha scritto:
>Can you try this apk out and see if it installs? I've updated the
>build-tools used locally and changed the version number, besides that
>there are no other changes from the latest release.
>
>[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1656669/app-release.apk.zip)
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/loyalty-card-locker/issues/183#issuecomment-359840789

-- 
Inviato dal mio dispositivo Android con K-9 Mail.
-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by brarcher** [comment]
It would seem that with the new Gradle Android plugin, the version of build-tools is selected [automatically](https://developer.android.com/studio/releases/gradle-plugin.html):
> With this update, you no longer need to specify a version for the build tools—the plugin uses the minimum required version by default. So, you can now remove the android.buildToolsVersion property.

The latest plugin does not use build tools 27.0.1 or later. So, when I build locally and when F-Droid builds it will use whatever version it wants.

Lets try one more thing. The bug report mentions that the following flag may also avoid the issue:
```
-Pandroid.enableAapt2=false
```
The attached APK builds with that flag. Can you see if it is able to install?

[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1658064/app-release.apk.zip)

If that works I may be able to set the property in the build so F-Droid also uses it.

**Comment by surferjoeit** [comment]
Hello,
I tested It and it works.
Many thanks!

Il 24 gennaio 2018 01:20:07 CET, Branden Archer <notifications@github.com> ha scritto:
>It would seem that with the new Gradle Android plugin, the version of
>build-tools is selected
>[automatically](https://developer.android.com/studio/releases/gradle-plugin.html):
>> With this update, you no longer need to specify a version for the
>build tools—the plugin uses the minimum required version by default.
>So, you can now remove the android.buildToolsVersion property.
>
>The latest plugin does not use build tools 27.0.1 or later. So, when I
>build locally and when F-Droid builds it will use whatever version it
>wants.
>
>Lets try one more thing. The bug report mentions that the following
>flag may also avoid the issue:
>```
>-Pandroid.enableAapt2=false
>```
>The attached APK builds with that flag. Can you see if it is able to
>install?
>
>[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1658064/app-release.apk.zip)
>
>If that works I may be able to set the property in the build so F-Droid
>also uses it.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/loyalty-card-locker/issues/183#issuecomment-359977576

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by brarcher** [comment]
Can you try one more build for me? This build uses the same configuration change but it is in a file instead of a command line argument. If this works it means that F-Droid will build the apk with the workaround, and I'll cut a release with the change.

[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1661636/app-release.apk.zip)

**Comment by surferjoeit** [comment]
It works. Thanks for the help.

Il 24 gennaio 2018 21:56:34 CET, Branden Archer <notifications@github.com> ha scritto:
>Can you try one more build for me? This build uses the same
>configuration change but it is in a file instead of a command line
>argument. If this works it means that F-Droid will build the apk with
>the workaround, and I'll cut a release with the change.
>
>[app-release.apk.zip](https://github.com/brarcher/loyalty-card-locker/files/1661636/app-release.apk.zip)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/loyalty-card-locker/issues/183#issuecomment-360270468

-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by brarcher** [comment]
Thanks for helping check!
