### ISSUE TITLE
Is the database vacuumed?

### ISSUE THREAD

**Issue by bracuphoth** [brarcher/loyalty-card-locker#189]
Lately I receive a lot of packages in mailboxes. Which I open with barcodes. And I use LCL to store these. But I figure out that the temporary codes stored than deleted are by now twice as many loyalty cards I have in stock. So

How do I vacuum the database?

**Comment by brarcher** [comment]
Is this to say that the database is leaking cards which you do not see on the main page of the app? If that is the case, it is a bug that needs to be addressed. I've not seen this myself; can you provide more details, such as Android version, app version, and any information about what you are observing which indicates the leak?

**Comment by bracuphoth** [comment]
No leaking observed. But as I do not have access to the actual database, I can't say. I keep adding barcodes for one time use to open a locker. I can't check if the database keeps growing by marking the deleted items deleted for the sake of speed, or if it actually deletes the rows.

**Comment by brarcher** [comment]
I'm confused as to the nature of your issue. If you are not observing a leak, what do you mean by:

> But I figure out that the temporary codes stored than deleted are by now twice as many loyalty cards I have in stock.

Can you give some steps to reproduce what you are seeing, and what outcome you are observing? If you can show a picture (with barcodes blacked out, if you need) that may also help.

> I can't check if the database keeps growing by marking the deleted items deleted for the sake of speed, or if it actually deletes the rows.

It should be deleting the rows. If one adds a card, exports a backup from the Export/Import view, deletes a card, then imports the backup, the previously deleted card will re-appear.
