### ISSUE TITLE
Add About-Screen with important Informations

### ISSUE THREAD

**Issue by SecUpwN** [brarcher/loyalty-card-locker#19]
@brarcher, I am missing an About-Screen in *all* your apps containing the following Information:

* Version of the App and License
* Clickable link to the GitHub repo
* Other Info about used Libraries

I consider this especially important to ensure proper bug reports and attract more developers. Thanks!

**Comment by brarcher** [comment]
This should be resolved in the most recent release, available on F-Droid. Re-open this issue if you feel otherwise.
