### ISSUE TITLE
Barcode too small

### ISSUE THREAD

**Issue by glesik** [brarcher/loyalty-card-locker#202]
When I enter 17+ digit number, the barcode doesn't stretch to fill the screen width making it too small to scan in portrait orientation:

![lck_17](https://user-images.githubusercontent.com/1032430/36326115-0b2aabfc-136b-11e8-9523-dbb063bf488e.png)

When it's 16 digits or less, everything's fine:

![lck_16](https://user-images.githubusercontent.com/1032430/36326170-2b0790c0-136b-11e8-9877-2e7014439ae2.png)

Would it be possible to enlarge it? So far the only way to scan it is to start the app in landscape mode (see also #67) which makes the barcode somewhat larger, but also not full width:

![lck_17_h](https://user-images.githubusercontent.com/1032430/36326731-33093dee-136d-11e8-8cbe-cef1c7720c7e.png)

I see this behavior on both 4.5" 1280x720 and 5.5" 1920x1080 screens. The actual barcode in question is 18 digits from IKEA Family card.

**Comment by brarcher** [comment]
Changes have been added to v0.22 which should address this. If the issue persists, please re-open this issue.
