### ISSUE TITLE
Maximize the brightness

### ISSUE THREAD

**Issue by CooperBarrett** [brarcher/loyalty-card-locker#21]
Hello, 
Will you he can add this functionality: 
Maximize the brightness when selecting the card. 
Or have a button that allows you to do so.
The scanners detect barcodes with improved brightness.

Thank you and good luck

**Comment by Almtesh** [comment]
Yes, good, show a little barcode on the card's page, when you click it, you show the barcode fullscreen, landscape and maximum brightness, with a line showing in large characters the number human readable.

**Comment by brarcher** [comment]
These are good suggestions. I'll think on them and how best a user would navigate through the app to finally expose a barcode with maximum brightness. Probably will not get to it right away.

Has anyone used this app successfully at a store? I find that the displayed barcode can be captured by a some barcode scanners,  for example some hand held devices at a store, and devices that take a picture such as another phone. However, scanners with a scanning laser do not seem to pick up the displayed barcode well.

**Comment by Vebryn** [comment]
I use it successfully at mall. It maybe depends on screen size ? barcode type and length ?

**Comment by Almtesh** [comment]
@Vebryn actually, that only depends on screen resolution. If you want to validate the system work, try to read a Ikea card. They have the longest barcode I saw.

**Comment by Vebryn** [comment]
No problem actually, I will try :)

**Comment by bracuphoth** [comment]
Very important. Every place I have tried the app - the code was unreadable unless the screen light was maxed out. So, maybe a button to 'light up' the entry when viewing the entry, than back to the previous level?

**Comment by brarcher** [comment]
A change to automatically set the brightness to maximum while viewing a card is now in master, and should appear in the next release. When that is released, kindly let me know if it resolves your issue and if scanning from some barcode scanners is more reliable.
