### ISSUE TITLE
Card capture sound does not respect system-wide silent or vibration mode

### ISSUE THREAD

**Issue by shapirus** [brarcher/loyalty-card-locker#214]
Whenever I add a new card via capturing it with a camera, a loud capture notification sound is played. This happens with no regard to whether silent or vibration-only mode is currently active, which sometimes may be undesirable.
It would be nice if the application did respect that setting and was silent or made a short vibration (or maybe as well set the notification volume accordingly to the current ringtone volume setting?), respectively, upon adding a card. Or there could be an option in the settings menu to control this behavior.

**Comment by brarcher** [comment]
I think that the beeping is a newer feature of the barcode scanning library I used, and it happens to default the setting to 'true'. Now that you mention it I looked into it, and the beep can be disabled. For now, I'll just turn off the beep, as that was the behavior in the past and I personally do not care for the beep. If someone really wants the beep later, it can be configured with a setting.

**Comment by brarcher** [comment]
This fix will appear in the next release.
