### ISSUE TITLE
Allow brightness for showing cards to be controlled in the settings

### ISSUE THREAD

**Issue by jghq** [brarcher/loyalty-card-locker#218]
I only have a handful of cards in use but was glad to see an open source, f-droid listed app without weird permissions. Thanks and thumbs up!

I think a control to add a set amount or percentage of brightness when viewing a card would be nice instead of always having it at maximum.

**Comment by brarcher** [comment]
> Thanks and thumbs up

Glad it is useful to you. (: 

The intention of maxing out the brightness is to theoretically improve the ability of the barcode scanner to see the barcode and successfully scan it. These are discussed in https://github.com/brarcher/loyalty-card-locker/issues/21.

What is the use case for having the brightness when viewing a card be configurable? Is it that you would rather the brightness setting in Android not be overridden?

**Comment by shapirus** [comment]
> What is the use case for having the brightness when viewing a card be configurable?
When I first tried this app (suggested by f-droid, btw, which I also tried then for the first time), it was quite uncomfortable to have the display at the maximum brightness, because it was night and very low ambient light at that time.
Whether this use case deserves a special option, I cannot say :)

**Comment by brarcher** [comment]
Ok, I understand. It sounds like having a setting to enable/disable the brightness override is reasonable.

What do you mean that fdroid recommended the app?

**Comment by shapirus** [comment]
> What do you mean that fdroid recommended the app?

The F-Droid app showed (and I think still shows) loyalty card locker somewhere in the top of the list of the available apps on the main screen. Freshly installed, default settings. Maybe within the first ten or twenty apps. That is actually how I came across it. I wasn't searching for anything in particular, and there it was, and I thought that it was a nice idea to have all my cards, which I always tend to forget to carry around, in my smartphone.
That is probably going to bring you some new users like myself.

**Comment by jghq** [comment]
Sorry about the delay in responding. I understand that the intent is to make it more readable for the scanner, but I find it's often way too much.

At a minimum, I'd like an option to not override the existing setting. Another possibility is an option to add a user configurable amount to the existing brightness level, including 0.

**Comment by jghq** [comment]
With the full understanding that a creator of an open-source app has no obligation to make any changes, is this something that can be expected for this app?

**Comment by brarcher** [comment]
Sometimes the squeaky wheel gets the grease. (:  I appreciate the no-pressure mindset.

Recently a settings menu was added for the new layout. Adding a new setting and controlling the brightness should be pretty straight forward. Let me see if I can do in the next few minutes while I have some time.

**Comment by brarcher** [comment]
Yep, it was pretty simple. I'll will appear in the next release of the app.

**Comment by jghq** [comment]
Well this is awesome. Thank you.
