### ISSUE TITLE
enhancement: possibility to make a desktop shortcut to the card directly

### ISSUE THREAD

**Issue by bieniekmateusz** [brarcher/loyalty-card-locker#223]
Some cards are used more often than others. A shortcut on the screen directly to the card could be handy. 

And thank you!

**Comment by brarcher** [comment]
This should already be supported and was merged in https://github.com/brarcher/loyalty-card-locker/pull/161, available in [v0.16](https://github.com/brarcher/loyalty-card-locker/releases/tag/v0.16).

Depending on your home screen, to add a shortcut to a specific app you will need to add a loyalty card  shortcut via the widgets menu:

![image](https://user-images.githubusercontent.com/5264535/37228580-1ff21c74-23af-11e8-881f-631a672b15a6.png)

![image](https://user-images.githubusercontent.com/5264535/37228595-2e3a798e-23af-11e8-98dd-275386e0b3ba.png)

When added to the home screen it will launch an activity with a list of all the cards you have:

![image](https://user-images.githubusercontent.com/5264535/37228620-3d851f48-23af-11e8-89a1-4651a8555381.png)

Touch the one you want, and the shortcut on the home screen will launch it directly:

![image](https://user-images.githubusercontent.com/5264535/37228654-5606c7f6-23af-11e8-9f98-1fb495637b81.png)

Is this what you were asking about? If not, please re-open and let me know.
