### ISSUE TITLE
alternativeto.net name does not match the name in Google Play store

### ISSUE THREAD

**Issue by bieniekmateusz** [brarcher/loyalty-card-locker#224]
The name of the app is now "Loyalty Card Keychain" but the alternativeto.net uses a different name. Would make it easier to find if the two were matching. 
https://alternativeto.net/software/loyalty-card-locker/?loginAction=loyalty-card-locker 

Cheers, Mat

**Comment by brarcher** [comment]
I'm not sure what alternativeto is, but I have not posted the application there. The only locations which I intentionally publish the application to are F-Droid, Google Play, and GitHub (releases page).

The application was originally called Loyalty Card Locker, but was re-named later to make more sense. I may suggest that you send a note to the owner of alternativeto and ask that the name be updated to match the officially supported locations.

**Comment by bieniekmateusz** [comment]
Thanks, apparently it is community maintained. I send a request to update it.

**Comment by brarcher** [comment]
My guess is they get the name from the GitHub project name, which is still loyalty-card-locker. That did not change when the project's name changed. I was reluctant to do that, as the name on GitHub is more of a technical matter and does not need to affect the branding of the application itself.
