### ISSUE TITLE
Manually add a code

### ISSUE THREAD

**Issue by PanderMusubi** [brarcher/loyalty-card-locker#23]
Not all loyalty cards have barcodes. Please allow for adding a code manually.

**Comment by brarcher** [comment]
Help me understand your proposed use case.

If there are loyalty cards which do not have barcodes, how does the store scan the card? Is it a magnetic strip, or something else?

If one manually enters a value for a card entry, and that value does not represent a barcode, what is displayed when the card entry is clicked? Is there a box with the entered data but no attempt to display any type of barcode? Will a clerk at a store enter this text manually at the point of sale?

**Comment by PanderMusubi** [comment]
Yes, it would be processed manually. I think the field Note can handle this as well. So please allow for an additional field called Note and make the scanning not a requirement for creating a card, please. This is also handy when you are managing your cards (creating some) but are not in the possibility to scan the cards.

**Comment by taranarmo** [comment]
There are cards with bad barcodes not readable by smartphone

**Comment by PanderMusubi** [comment]
yes, in that case entering the code manually must be possible too

**Comment by brarcher** [comment]
Would having the Note field be sufficient, or should there be a way to manually enter barcode number/data then select which barcode type it is? There are a number of barcode types, so one would need to iteratively determine which type is the goal. Perhaps all supported barcode types which are valid for the given data and the application supports would be displayed, then the user selects the one which best matches the barcode on the loyalty card? Or, is there another easier mechanism someone may propose?

**Comment by PanderMusubi** [comment]
Some other apps allow to enter it manually. For me personally the note field is fine. Perhaps ask more users.

**Comment by brarcher** [comment]
A Note field is now available. If you feel that adding a barcode manually is still necessary, please re-open this issue.

**Comment by SecUpwN** [comment]
@PanderMusubi, please re-open this Issue. I was just filing this until I noticed that your Issue already existed. @brarcher, yes, please add a field for manually adding the customer number. If you still wonder which cards might have no barcodes but a huge number, have a look at the `IKEA Family Card`. The cool thing about your app would be that it will then *generate* a barcode, which may be scanned at IKEA. 😼

**Comment by brarcher** [comment]
As of v0.6 one may manually add a barcode. If you feel that this not adequate or can be improved, please re-open this issue or open another issue.
