### ISSUE TITLE
new feature : possibility to scan qr-code

### ISSUE THREAD

**Issue by GaelLeboeuf** [brarcher/loyalty-card-locker#230]
Hello,
One of my loyalty card (sncf - french railway) use qr-code instead of barcode.
Scanning a new card is possible only for barcode and adding my card number manually does not generate the right qr-code.
Do you think it is feasible?
Many thanks for that great app'.
Best.

**Comment by brarcher** [comment]
The app does support scanning qr codes. Are you finding that it is not scanning qr codes for you? Would you be able to attach an example? Additionally, if manually entering a code is not generating the qr code you expect can you attach a picture of what you expect and what you are getting?

**Comment by GaelLeboeuf** [comment]
Many thanks Brarcher.
While trying to take a screenshot, I realized that in order to capture a complex qr-code like the one I'm talking about, I need to fix it with the camera for a long time (like 10/15s)...then everything works fine.
The reason why entering manually my card number doesn't work is because the QR-code of my card includes much more information (my name, the expiration date, etc...).
Issue solved!
Sorry for bothering you with that. 
You're doing a great job on this app' 
Many thanks!
