### ISSUE TITLE
new feature: optionally lock orientation on barcode display

### ISSUE THREAD

**Issue by rigid** [brarcher/loyalty-card-locker#231]
If you have auto orientation enabled, card readers can be confused when holding the phone next to it.
This could be fixed if one could choose a fixed orientation in the settings. I'd imagine something like:
Barcode orientation: auto/landscape/portrait

**Comment by brarcher** [comment]
Presently there is a lock icon in the menu when looking at a barcode, and clicking on it forces the orientation to portrait. I've not figured out how to determine if the screen is portrait or landscape, so only portrait is supported. For dense barcodes that is not very useful with the new screen layout.

If someone were interested in helping out here and adding a setting for it, it would make more sense and I'd be glad to review the pull request.

**Comment by rigid** [comment]
i can't provide a PR currently but for anyone willed to give it a go i'd point to [rf_analyzer](https://github.com/demantz/RFAnalyzer/blob/master/app/src/main/java/com/mantz_it/rfanalyzer/MainActivity.java). It's solved there using this snippet:

```
import android.content.pm.ActivityInfo;

String screenOrientation = preferences.getString(getString(R.string.pref_screenOrientation), "auto");
		if(screenOrientation.equals("auto"))
			setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
		else if(screenOrientation.equals("landscape"))
			setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
		else if(screenOrientation.equals("portrait"))
			setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
		else if(screenOrientation.equals("reverse_landscape"))
			setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_LANDSCAPE);
		else if(screenOrientation.equals("reverse_portrait"))
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_REVERSE_PORTRAIT);
```

**Comment by brarcher** [comment]
A setting was added in https://github.com/brarcher/loyalty-card-locker/pull/269 which can lock the orientation to portrait for all cards. Might this be sufficient?

**Comment by TheLastProject** [comment]
This issue can be closed, as it has been implemented and the original requester gave a :+1: to the "Might this be sufficient" question.
