### ISSUE TITLE
import bug

### ISSUE THREAD

**Issue by gitthubba** [brarcher/loyalty-card-locker#234]
Importing "from filesystem" opens WhatsApp, if its installed, instead of the file browser and vice versa for "use external application".

Tested with v0.23.2 on Android v8.1.0

**Comment by brarcher** [comment]
When the "from filesystem" button is pressed whatever activity is selected to handle Intent.ACTION_PICK is invoked. It would appear that WhatsApp is selected to perform that action in your case. I do not use WhatsApp, but does it have a file or gallery selection option? Maybe that is what it is being launched?

There should be a way to change which app responds to that intent. [This article](https://www.androidauthority.com/change-default-apps-android-2-633572/) give some advice. 

As for the "use external application", what do you mean "vice versa"? If WhatsApp is installed it does not get opened when clicking on "use external application"? That button starts whatever activity is registered to received the Intent.ACTION_GET_CONTENT intent with content type * (e.g. wildcard). If may be that WhatsApp is not registered for that intent.

**Comment by marcoM32** [comment]
This issue is still present in the last release, please fix it.

**Comment by TheLastProject** [comment]
Checking this on my own phone, it does seem the buttons are "swapped around".

Clicking "From Filesystem" suggests:
- WhatsApp
- Google Drive
- Ghost Commander

Clicking "Use External Application" opens Android's native file browser.

Do you see something similar, @marcoM32?

**Comment by marcoM32** [comment]
If I try to activate "Import from file system" see this content but the file manager is not displayed. 

![photo_2020-01-17_09-23-58](https://user-images.githubusercontent.com/16719549/72596744-afcc1600-390c-11ea-891a-792108a9b7c4.jpg)

Also in my opinion the buttons are swapped or the translation is not correct

**Comment by TheLastProject** [comment]
>Also in my opinion the buttons are swapped or the translation is not correct

Yeah, I agree. Thanks for the screenshot and confirming it happens on your device too. Android is... quite inconsistent especially between manufacturers so more people confirming it helps. I've created #346 to fix this.
