### ISSUE TITLE
Consider allowing adb backups

### ISSUE THREAD

**Issue by jody-frankowski** [brarcher/loyalty-card-locker#236]
I am not sure why it would be disabled, but right now adb backups seem to [be blocked](https://github.com/brarcher/loyalty-card-locker/blob/af3ce5a0ffa5a4b693683d3a65c4936637c20d37/app/src/main/AndroidManifest.xml#L20).

**Comment by brarcher** [comment]
Honestly, I do not know how the backup mechanism works and have never used it myself. Instead, I use the export mechanism in the app to output backup. If someone were interested in getting the adb backup mechanism to work and add some tests, I'd gladly review the pull request.
