### ISSUE TITLE
Extra field for client

### ISSUE THREAD

**Issue by PanderMusubi** [brarcher/loyalty-card-locker#24]
Please add a field under Store naned Client. For some stores people have multiple cards, each as a different client of that store, e.g. when working for multiple organisations. 

This would be an optional field and can be shown in the over behing the name of the store, separates by a space, hyphen and space.

**Comment by brarcher** [comment]
How about a field for "Note", which could be used to record other information about the specific card. It could record different Clients, or anything else. Would that work?

**Comment by PanderMusubi** [comment]
Yes, than the user can decide whatever extra data to store in there.

**Comment by brarcher** [comment]
v0.4 was release which now has an optional Note field. When this makes it way to F-Droid, let me know if it is what you were hoping for.

**Comment by PanderMusubi** [comment]
super, thanks!
