### ISSUE TITLE
Note cutoff when viewing a card

### ISSUE THREAD

**Issue by brarcher** [brarcher/loyalty-card-locker#241]
This is observed on the Pixel 2 XL:

![image](https://user-images.githubusercontent.com/5264535/39733998-4d2f02f2-5243-11e8-80e7-9d66b99d1873.png)

**Comment by egvimo** [comment]
I have the same issue with my Pixel 2.

**Comment by Ennoia11** [comment]
Hi,
same with a Xiaomi Mi A1. Do you need anymore information ?

**Comment by brarcher** [comment]
Probably no additional information is needed. I may not be able to get to fixing this; if someone from the community is able to submit a fix I'd be glad to review it.

**Comment by TheLastProject** [comment]
Can confirm this also happens on the Fairphone 3. The interesting part is that as soon as you tap the text of the note, the sizing becomes correct

**Comment by TheLastProject** [comment]
I just noticed that if I open a card, switch away from the app and switch back, the layout is suddenly correct too. Just leaving that here in the hope it helps someone
