### ISSUE TITLE
Translations are mixed. Spanish is confused with another language.

### ISSUE THREAD

**Issue by javiertury** [brarcher/loyalty-card-locker#243]
The file with the [Spanish translations](https://github.com/brarcher/loyalty-card-locker/blob/master/app/src/main/res/values-es/strings.xml) is wrong. It contains translations for another language. I think that language is Slovak.

**Comment by brarcher** [comment]
Crap. You are right. Sorry about that. Thanks for pointing it out. I'll redo the translation files in case others are also wrong.

**Comment by brarcher** [comment]
I must not have been careful enough when pulling translations fro Transifex. The Spanish translations appear to be the only ones I botched. I'll push an update out today with the corrected translations.

**Comment by javiertury** [comment]
Wow, that was quick. Thanks a lot.

**Comment by brarcher** [comment]
> Wow, that was quick

Just lucky. I had a few minutes, its an easy fix, and I'm a little embarrassed that Spanish users may not be able to use the app well as the language was wrong. Anyway, a release with the fix is out now, so you can update if you need. (Or, if you use F-Droid, it will be a few days).
