### ISSUE TITLE
[Feature Request] Share one or more entries

### ISSUE THREAD

**Issue by shtrom** [brarcher/loyalty-card-locker#249]
It would be good to be able to share one or more entries using standard share intents, in a way that would allow a contact to import them into their own locker.

**Comment by brarcher** [comment]
To repeat the request back, you would be interested in having the app accept Share requests, and if valid data is received it will import the cards?

As for what the data should be, the import/export mechanism in the app presently only operates on CSV files. Would importing that data be sufficient?

**Comment by shtrom** [comment]
On Sat 02 Jun 2018 at 08:28:20 -0700, Branden Archer wrote:
> To repeat the request back, you would be interested in having the app accept Share requests, and if valid data is received it will import the cards?

Yeah, that's the other side of the request I guess (:

> As for what the data should be, the import/export mechanism in the app presently only operates on CSV files. Would importing that data be sufficient?

CSV files would be Just Fine(tm). No need to complicate I think.

However, it may be necessary to have a way to represent
properly-formatted CSV files? Or just accept CSV and display an
error message if they don't conform to the expected schema?

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by brarcher** [comment]
> properly-formatted CSV files

[RFC4180](https://tools.ietf.org/html/rfc4180) defines what a valid CSV file looks like. The app further adds to this, expecting data to be in certain columns. An error message when an import fails would be fine. I think that the existing import/export mechanism in the app does this currently.

> Yeah, that's the other side of the request I guess (:

Are you also looking for an export mechanism outside of what the app does today? If so, how would you see it working?

**Comment by shtrom** [comment]
On Sat 02 Jun 2018 at 19:31:52 -0700, Branden Archer wrote:
> Are you also looking for an export mechanism outside of what the app
> does today? If so, how would you see it working?

I think the export is orthogonal to this, and does its job well, but I
think the idea here would really be to send CSV data of the selected
entry(ies) to a share intent, and see whatever picks it up.

That said, I don't know if something needs to be done on the receiver's
side so it shows up as able to _open_ CSVs received from contact, or if
this is the same as receiving CSV-formatted share intents from other
local apps.

-- 
Olivier Mehani <shtrom@ssji.net>
PGP fingerprint: 4435 CF6A 7C8D DD9B E2DE  F5F9 F012 A6E2 98C6 6655
Confidentiality cannot be guaranteed on emails sent or received unencrypted.

**Comment by brarcher** [comment]
Ideally, if this app were updated to receive an intent with CSV data it would be no different that when the app imports a CSV file directly.

I'll probably not have a change to get to this for awhile. If someone were interested in working on this, I could help review the pull request.

**Comment by TheLastProject** [comment]
I would personally prefer this to be implemented as an URI scheme, something like:
`homepage.tld/import/?all_csv_values_here`

This would ensure that when sharing to users who do not have the app installed yet, we can explain them they need this app to accept the card shared to them.

Does this project have a homepage at all? I couldn't find one.

**Comment by brarcher** [comment]
> Does this project have a homepage at all? I couldn't find one.

The GitHub page is the project's homepage. (:

**Comment by TheLastProject** [comment]
I mean, that's fair, but it'll not be great for non-technical users to end up on the GitHub page because there's a lot of code and the install buttons are very far away. Could you maybe set up a GitHub Pages site for the project? Then you could share with URLs like "https://loyalty-card-locker.github.io/import/?all_csv_values" and people who don't have the app installed will see the download link on app stores without having to scroll.
