### ISSUE TITLE
Manually adding card doesn't work

### ISSUE THREAD

**Issue by StalenBas** [brarcher/loyalty-card-locker#272]
When I try to enter a card manually, I first copy the card number and then select the type of Barcode. Pressing the desired Barcode type returns me to the "Add loyalty card" screen. If I then press the save icon, however, it says "No card ID entered".

I tried rebooting the phone to no avail. Phone is a Huawei Mate 10 Pro, running Android 8.

**Comment by brarcher** [comment]
Oh, I see, you are right. Thanks for reporting this. I'll have an update out shortly to resolve this.

**Comment by brarcher** [comment]
This should be resolved in the next release, which should be out in a bit.
