### ISSUE TITLE
Save related coupons

### ISSUE THREAD

**Issue by Lucki** [brarcher/loyalty-card-locker#279]
Some stores serve coupons as barcodes. Would be nice to be able to store them along the cards.

<img src="https://user-images.githubusercontent.com/1408843/47157368-752e9480-d2e9-11e8-9ade-3c1457dcf044.png" width="300">

I'm often using [Revolution IRC](https://github.com/MCMrARM/revolution-irc) which channel handling could be useful here to seperate the main barcode view. You could swipe across all different cards with customizable names (#264) until you're at the coupons section. That's a simple scrollable list with customizable notes above.

Of course they often have an expiration date so this is a bit related to #229. I've thought of adding a red color to the barcode which then can deleted by a long press. Maybe a striked out text or something similar would work too.

<img src="https://user-images.githubusercontent.com/1408843/47156538-9f7f5280-d2e7-11e8-8ad7-b56a24e1721b.png" height="300"> <img src="https://user-images.githubusercontent.com/1408843/47156544-a4440680-d2e7-11e8-8b3f-19bda5a67b0b.png" height="300"> <img src="https://user-images.githubusercontent.com/1408843/47156545-a4440680-d2e7-11e8-9bbb-725b84f457ce.png" height="300">

**Comment by Lucki** [comment]
If you've actually got a physical card sometimes your store sends coupons to you including a barcode and an online code for your next purchase. At the store you would see that there is a coupon you might have forgotten already. This would be my use case, I think.

You're right with some stores want you to leave the coupons in the store but in my experience that's mostly for shops you don't have a loyalty card for. For example advertising magazines or other general advertisements in your mailbox.
We don't have to think about reimplementing their own apps. That's way beyond the purpose of this app.

But it's perfectly fine for me if you're saying that you're not going to work on this. There are enough open issues already ;)

**Comment by devurandom** [comment]
Another use case would be travel groups: ligi/PassAndroid#91

This is possibly a duplicate of: brarcher/loyalty-card-locker#166

**Comment by Lucki** [comment]
Implemented by https://github.com/TheLastProject/Catima/pull/71
