### ISSUE TITLE
Feature request: Add an option to not have a barcode displayed

### ISSUE THREAD

**Issue by dpeukert** [brarcher/loyalty-card-locker#291]
Some of my loyalty cards only have a magnetic strip and a card ID on them, therefore not requiring the barcode. It would be nice to have an option to only have the card ID displayed.

**Comment by TheLastProject** [comment]
I wrote code for this in https://github.com/TheLastProject/loyalty-card-locker/tree/feature/barcodeless_cards which adds a "This card has no barcode" button in the edit card screen but I after finishing this I started to wonder... what's the actual use case? Is there any store that will let you in with just the number? If it has a magnetic strip, won't they require you to use that magnetic strip?

**Comment by dpeukert** [comment]
Yep, my usecase is a Czech fast food chain (https://www.bb.cz/), I've been to a couple of their locations and the number by itself was always enough. I would guess the number is all that is stored on the strip anyway, so they probably don't consider that an abuse vector.
