### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by Airon90** [brarcher/loyalty-card-locker#3]

**Comment by brarcher** [comment]
A [merge request](https://gitlab.com/fdroid/fdroiddata/merge_requests/1183) to F-droid has been opened, and is waiting for approval. Probably in a few days it will be available on F-droid.

**Comment by Airon90** [comment]
:+1:

**Comment by brarcher** [comment]
This is now available on F-Droid [here](https://f-droid.org/repository/browse/?fdcategory=Money&fdid=protect.card_locker)
