### ISSUE TITLE
Import other app's cards

### ISSUE THREAD

**Issue by xballiet** [brarcher/loyalty-card-locker#301]
Hello,

Is there a way (or would it be possible to have a way) to import cards from another app (like Stocard for example) ?

Thanks in advance !
Xavier

**Comment by brarcher** [comment]
I've not used Stocard myself, only heard of it. Does Stocard allow users to export card data to file? If so, and if one were interested in reverse engineering the format and creating a change that adds support, I've be up for reviewing it.

**Comment by xballiet** [comment]
Sadly enough, there's apparently no export feature in Stocard and I haven't found yet the folder where data are stored (or perhaps there is no such folder...)
So I guess that I will have to add manually all my cards in Loyalty Card Keychain.

**Comment by ilpol984** [comment]
Hello, you can request the export to stocard support. They will produce it within one month. Regards,
