### ISSUE TITLE
Starbucks ☕ barcode isn't recognized

### ISSUE THREAD

**Issue by alexanderadam** [brarcher/loyalty-card-locker#332]
The code looks uncommon, though but they are using it for the app and for some promotions.

Here are some examples. I hope these are really just examples and not real codes. I will just link them and not upload the examples here to be on the safe side:

* [`6065 6015 6861 8783`](https://www.flickr.com/photos/25095603@N07/5401935326)
* [`6061 0069 1352 2430`](https://www.thestar.com/news/world/2011/08/11/man_offers_his_starbucks_card_online_to_everyone_is_it_for_real.html)
* [`6108 …` (I'm not sure why the hide the number but show the full code)](https://www.verizonwireless.com/support/knowledge-base-139517/)
* [`… 1346`](https://dribbble.com/shots/2431049-Windows-10-Phone-App-Starbucks)
* [another one](http://www.techonthego.co.uk/wp-content/uploads/2012/10/starbucks-passbook-card-integration_thumb.png)
* [some offer code](https://www.twipu.com/Mr__Warmth/tweet/1082197587267125248)

I tested it with mine as well and loyalty card locker didn't recognize it.

**Comment by TheLastProject** [comment]
I just scanned the first one and it scanned just fine to me. It seems to be PDF417, which is supported.

**Comment by alexanderadam** [comment]
Strange, it doesn't recognize the first one for me.
You mean `6065 6015 6861 8783`, right?

I'm using [version `0.25.4` from F-Droid](https://f-droid.org/en/packages/protect.card_locker/#0.25.4) (which is the latest version available on F-Droid).
Do I have to activate or configure something?

**Comment by TheLastProject** [comment]
Nope, works out of the box for me.

Are you sure the loyalty card isn't in any way obscured and is properly lit? I often see people try to scan a barcode while their phone cover creates a lot of shadow over the imagine, making the scanner unable to pick up the barcode.

See https://imgur.com/a/cnu0P8K for a recording of me scanning the first code.

**Comment by alexanderadam** [comment]
Sorry, my fault.
It seems to be _much_ more difficult to scan a Starbucks code than any other QR code that I have.

I got it working indeed after trying various angles, although my camera should be totally fine (Samsung S9).

So I will close this.

**Comment by TheLastProject** [comment]
Glad you got it working! :)
