### ISSUE TITLE
Cannot convert a card with a barcode to a card without a barcode

### ISSUE THREAD

**Issue by brarcher** [brarcher/loyalty-card-locker#335]
If a card is created with a barcode, then later is edited to select "This card has no barcode", the update does not work. As a result, a card with a barcode can never be changed to a card without a barcode.

**Comment by brarcher** [comment]
For reference, the change which introduced barcodeless cards is https://github.com/brarcher/loyalty-card-locker/pull/324.

**Comment by brarcher** [comment]
@TheLastProject, are you able to reproduce this behavior?

**Comment by TheLastProject** [comment]
Huh, yeah, I can reproduce this issue too. I'll try to look into this soon
