### ISSUE TITLE
NPE when sharing a card

### ISSUE THREAD

**Issue by brarcher** [brarcher/loyalty-card-locker#342]
The following exception is reported multiple times from Beta users from Play on release [v0.26](https://github.com/brarcher/loyalty-card-locker/releases/tag/v0.26):

```
java.lang.NullPointerException: 
  at protect.card_locker.ImportURIHelper.toUri (ImportURIHelper.java:60)
  at protect.card_locker.ImportURIHelper.startShareIntent (ImportURIHelper.java:77)
  at protect.card_locker.MainActivity.onContextItemSelected (MainActivity.java:210)
```

This is the following line:
```
uriBuilder.appendQueryParameter(HEADER_COLOR, loyaltyCard.headerColor.toString());
```

Android Studio does surface a warning that headerColor may be null, but that may be a general warning, as nothing in the contract to toUri prevents a card field from being null. The question is, under what conditions is the header color null?

**Comment by brarcher** [comment]
@TheLastProject, are you interested in taking a look at this issue with sharing loyalty cards? If not, I can take a look when I have time. 

Right now v0.26 is in Beta. I'd like to address this issue before taking the new features out of Beta.

**Comment by TheLastProject** [comment]
It is allowed to be null in the database so my guess would be that these are old loyalty cards saved before the header and title colour fields were introduced. The rest of the code has null checks for the header fields to deal with this.

I will soon (probably this evening) patch this as follows:
- It will not add headerColor and headerTextColor to the uri if they are null
- Add tests to ensure that this situation doesn't crash sharing and that those missing parameters don't cause importing to fail
