### ISSUE TITLE
"About" not translated

### ISSUE THREAD

**Issue by comradekingu** [brarcher/loyalty-card-locker#353]
The field "About" is untranslated in the latest version (0.27) in nb_NO, despite being translated a year ago.
https://hosted.weblate.org/translate/loyalty-card-keychain/translations/nb_NO/?checksum=92959093571d1319
Same for "Theme", the copyright field, also"Skip" and "Done" for the intro screens

**Comment by brarcher** [comment]
Ah, I recall the discussion from https://github.com/brarcher/loyalty-card-locker/pull/280 about this. The Weblate account was setup for this project, but I never followed through to add a script to pull down the translations. For example, here is my script for transifex:

https://github.com/brarcher/tools/blob/master/transifex/transifex-pull

I've manually pulled down the nb_NO translations from Weblate and created a pull request.
