### ISSUE TITLE
file or owncloud export

### ISSUE THREAD

**Issue by Vebryn** [brarcher/loyalty-card-locker#36]
Hi,

Great app! An enhancement, is it possible to add a sync to Owncloud or at least a file export?

Currently, we have to sync app' sqlite db.

Best regards

**Comment by brarcher** [comment]
This should be resolved in the most recent release, available on F-Droid. Re-open this issue if you feel otherwise.

**Comment by Vebryn** [comment]
Thank you, it's working fine :)
