### ISSUE TITLE
Successful export message is horrible

### ISSUE THREAD

**Issue by 532910** [brarcher/loyalty-card-locker#367]
`239` --- what is this? I've asked to save it as `LoyaltyCardKeychain.csv` and the app saved it so!

![image](https://user-images.githubusercontent.com/14617699/84606561-db4d2f80-aeaf-11ea-86fb-6bc99a8559fc.png)

**Comment by brarcher** [comment]
Ah. At one point the app saved the file to a fixed location. Later the app was updated to pick where the location could be. This means that another app controls the path. As Android some time ago added protections that prevent the sharing of literal paths, content providers are used instead.

I agree, this message (which prints out the content provider path) is not that helpful. Maybe there is a way to resolve the URI to a path on the file system, not sure. Maybe it should just say it was successful now and not try to show the path.

**Comment by TheLastProject** [comment]
I'd say let's not resolve the path. The user just chose where to save and even if we can resolve it, `/storage/emulated/12344/file.csv` will probably still not clearly convey "root of SD card" to most users as most file managers won't ever show such paths.

I can patch this this week, maybe even today after work. It's a pretty simple patch.

**Comment by 532910** [comment]
For the first, the path should not be shown, as a fast and easy solution.

For the second, we could discuss should it be shown at all. But I think it should not.
