### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [brarcher/loyalty-card-locker#380]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 7  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on loyalty-card-locker (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve loyalty-card-locker's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by brarcher** [comment]
You are welcome to send me the gists.

**Comment by misterAnderson90** [comment]
Hi, Branden

In the same way [gift_card_guard](https://github.com/brarcher/gift-card-guard/issues/51), the CognyCrypt reported 7 issues on loyalty-card-locker related to Google's Guava libraries.  

I'll raise an issue there instead. 

Please let me know if you are interested in receiving these warnings.
