### ISSUE TITLE
Other app with the same name and a disturbingly similar logo on the Google Play Store but different privacy guarantees

### ISSUE THREAD

**Issue by Arkanosis** [brarcher/loyalty-card-locker#385]
Hi!

Just a heads up that there's another app on the Google Play Store that has exactly the same name and a very similar logo (blue background, card, person with a crown, two stars on the left…), but unlike the original “Loyalty Card Keychain” which has *never* collected any data and *never* displayed any ad, this other app *does*.

This other app is published by “UniqueApp Technologies”  and unfortunately, it's often the only result you get when you search for “Loyalty Card Keychain” on the Google Play Store, because the original app was developed for an old Android release.

I can't leave a comment on that new app to let people know about the possible confusion (at least without installing it first, which I'm not going to do).

**Comment by bdr2** [comment]
Looks like that app is gone from the Play Store now. Here's the full listing of UniqueApp Technologies' apps in the Play Store:
https://play.google.com/store/apps/developer?id=UniqueApp+Technologies

I see that it is still on a few (disreputable) apk download sites, though.

**Comment by Arkanosis** [comment]
Good, thanks for heads up!

The two first results I get for “Loyalty Card Keychain” now are the original app (the one from this repo) and “Catima” (a derivative of the original app with a distinctive name and a distinctive logo). Probably the best possible outcome.
