### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Vebryn** [brarcher/loyalty-card-locker#48]
Hi,

Is there a way to get new releases changelog ?

Best regards.

**Comment by brarcher** [comment]
I suppose it depends on what "get" means.

One may go to the [release](https://github.com/brarcher/loyalty-card-locker/releases) section of this project and see a brief changelog for each release.

In addition, there is an About page available from the landing page of the application:

![screenshot_2016-05-30-22-09-42](https://cloud.githubusercontent.com/assets/5264535/15661224/a86ee69a-26b3-11e6-96cb-e516bed17ae3.png)

The About dialog has a link for the Releases page on GitHub.

Is this sufficient, or were you thinking of something else? If something else, can you be more specific or give an example?

**Comment by Vebryn** [comment]
Great! I often look at a changelog.md on GitHub project page.

**Comment by brarcher** [comment]
I've added a CHANGELOG.md file. Let me know if it helps.
