### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by SecUpwN** [brarcher/loyalty-card-locker#5]
Hey @brarcher, please implement the follwoing `README` improvements here as well:

* Link an F-Droid button just like I added via pull request on another project called [Binaural Beats](https://github.com/GiorgioRegni/Binaural-Beats).
* Correct the sentence on your `README` to the following one (it should say *changes*, not "changed"):

>If there is any interest in improving this project, kindly submit a pull request with proposed changes.

**Comment by brarcher** [comment]
Improvements made. Thanks!
