### ISSUE TITLE
How do I delete entries?

### ISSUE THREAD

**Issue by bracuphoth** [brarcher/loyalty-card-locker#52]
I seem to be able to edit, but I can't figure a way to remove entries.

**Comment by brarcher** [comment]
This may not be obvious, but if you:

1) Click on a card to bring up the "View Loyalty Card" screen
2) Click the pencil icon in the top right to bring up the "Edit Loyalty Card" screen
3) Click on the trash can icon in the top right

the loyalty card will be removed.

If you think of a way to make this more obvious, or put another delete option elsewhere, please let me know.

**Comment by bracuphoth** [comment]
Thank you. Now that you told me, it is pretty obvious. No need to change anything.
