### ISSUE TITLE
Error with import?

### ISSUE THREAD

**Issue by shane-kerr** [brarcher/loyalty-card-locker#63]
I have installed LoyaltyCardLocker from F-Droid (version 0.7 reported), and exported the LoyaltyCardLocker data from another device. I copied this to the phone, and tried the "IMPORT" button, but get this message:

   Failed to import: /storage/emulated/0/LoyaltyCardLocker.csv

As far as I can tell, the files are identical. I only have 9 entries so it's not a huge deal to re-scan or recreate them somehow, but I'm happy to try to debug this. I don't really know where to start, since all I get is the "failed to import" message. :smile:

**Comment by brarcher** [comment]
If you are able to create a bug report after this happens and attach it to this issue? There should logs included which will indicate why the import failed.

**Comment by shane-kerr** [comment]
I don't know how to create a bug report. Where can I find some documentation on how to do that? (I didn't see anything in the application user interface...)

**Comment by brarcher** [comment]
I was hoping there would be a way to create a bug report from Android itself. I see in Android 6 that one can open the Setting application, navigate to Developer Options, then click on "Take but report" to create a bug report. If one did not have Developer Options unlocked, however, then this would not be as easy to do.

I suspect that the issue is the default import/export location is not where the file is located. Someone else has request to identify where the import/export location will be (https://github.com/brarcher/loyalty-card-locker/issues/61). When that is complete likely the issue you are running into will not exist.

**Comment by shane-kerr** [comment]
I had a look at the bug report myself, and I found the pertinent part of the text file was this:

```
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker: Failed to input data
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker: protect.card_locker.FormatException: Failed to parse field: _id
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.CsvDatabaseImporter.extractInt(CsvDatabaseImporter.java:100)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.CsvDatabaseImporter.importLoyaltyCard(CsvDatabaseImporter.java:111)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.CsvDatabaseImporter.importData(CsvDatabaseImporter.java:32)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.MultiFormatImporter.importData(MultiFormatImporter.java:38)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.ImportExportTask.performImport(ImportExportTask.java:68)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.ImportExportTask.doInBackground(ImportExportTask.java:125)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at protect.card_locker.ImportExportTask.doInBackground(ImportExportTask.java:19)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker:     at java.lang.Thread.run(Thread.java:818)
11-04 13:52:46.827  8524  5078 E LoyaltyCardLocker: Caused by: java.lang.NumberFormatException: Invalid int: "<C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80>
<C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0>
<80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80>
<C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0><80><C0>
```

That goes on for quite a few more lines. :smiley:
 
I scratched my head, then looked at the file. I got it by using the copy & paste feature of the Amaze file manager, which was converting the 439-byte file into a 60 kilobyte file with lots of crap at the end.

So anyway, after using a different way to copy the file the import works great, and helped me discover a bug in a different program.
