### ISSUE TITLE
enhancement - accept code from sharing menu

### ISSUE THREAD

**Issue by lgasp** [brarcher/loyalty-card-locker#64]
I'm an user of your app, so, thank you for the effort.

As it is now, when I want to enter e new card, I scan it with barcode scanner (or something like it), then copy the resulting code to clipboard, and finally paste it in a new entry in Loyalty Card Locker.

Would it be possible to insert a new code in the app using the Android sharing menu from a barcode scanning app?

**Comment by brarcher** [comment]
> Would it be possible to insert a new code in the app using the Android sharing menu from a barcode scanning app?

It would be possible. Note though that the Loyalty Card Locker has its own barcode scanner available. If one clicks "Capture Card" when adding a new card a barcode scanner will come up using the camera. Is this insufficient?

Are there other use cases where one may not be scanning a barcode and would need to get a barcode value from somewhere else (maybe a webpage) where sharing would be helpful?

**Comment by lgasp** [comment]
You are right, my bad. The italian translation for the capture bar is not clear, and I didn't recognise it. It's something like "save card". I will propose a modification in the translation file.

Well, as for now  I don't see a case where the sharing menu of a barcode would be helpful.

Thank you
