### ISSUE TITLE
Rescale the barcode

### ISSUE THREAD

**Issue by bracuphoth** [brarcher/loyalty-card-locker#67]
If I hold the phone landscape and somehow the sensor turns the screen portrait, the whole entry, including the barcode are scaled to fit the screen. Which makes perfect sense. But once the screen is back in landscape mode the barcode stays tight and won't scale back. This happens when starting from portrait mode. And most barcode readers have a hard time reading it with a tight picture.

**Comment by brarcher** [comment]
I do not entirely follow. What do you mean by "the barcode stays tight"? Can you attach an image to help explain?

**Comment by bracuphoth** [comment]
From State 1 it goes to State 2, instead of showing State 3. I hope it makes more sense now.

![state-1](https://cloud.githubusercontent.com/assets/20538778/20617192/680be4a0-b2df-11e6-8b90-9a37ef2540a3.png)
![state-2](https://cloud.githubusercontent.com/assets/20538778/20617193/681317ac-b2df-11e6-917e-aa04a71376d9.png)
![state-3](https://cloud.githubusercontent.com/assets/20538778/20617194/682e94dc-b2df-11e6-9da9-5db1275cd8d4.png)

**Comment by bracuphoth** [comment]
Should I look for a better example?

**Comment by brarcher** [comment]
I think the example is ok. Just not sure what is going on. On my test devices I do not see this behavior.

Can you tell me the type of device you are using, the version of Android, and the version of the application you are using? Maybe I can duplicate it in an emulator using the same Android version.

**Comment by bracuphoth** [comment]
Cyanogenmod 13 on a Motorola phone

**Comment by brarcher** [comment]
Oh, I see what you mean now. When I open a barcode the orientation the phone is in at that time shows the barcode at its largest, but when I rotate the phone it is smaller. If I then start with a different orientation and enter a barcode the size is different from before.

I did not notice that until now...

I'll look into what this is.

**Comment by bracuphoth** [comment]
That's it! When the card entry is open landscape -> portrait -> landscape and the barcode is at half width which makes at least some readers unable to read it.

Going back to the mail list, scrolling back to the card and opening the card entry all in landscape is not affected. Only if the rescaling is done with the card entry opened.

There is a workaround: forcing the landscape for the whole system while using the loyalty card locker.

**Comment by tobiasisenberg** [comment]
Any news on this issue?

**Comment by brarcher** [comment]
I've not looked into this issue further yet, so no news presently. If someone were interested in investigating and proposing a fix, I would accept the pull request.

**Comment by brarcher** [comment]
Changes have been added to v0.22 which should address this for the view which shows the barcode. It continues to exist on the screen which edits the card, but I expect that to be less of an issue and it is not the screen which is shown most of the time. 

If the issue persists in the latest release or is not satisfactory, please re-open the issue.
