### ISSUE TITLE
Encrypted card database

### ISSUE THREAD

**Issue by betsythefc** [brarcher/loyalty-card-locker#71]
I'd like to have the card database encrypted that can be set up with a pin/password on openning the application.

**Comment by brarcher** [comment]
Is the concern that the data is encrypted at rest, or that another user is unable to open the application without a password?

**Comment by logic** [comment]
In my case, I'd like the data to be encrypted at rest. I use Dropbox as simple method of syncing data like this, but data stored with them isn't end-to-end encrypted. Perhaps you could leverage [OpenKeychain](https://www.openkeychain.org/apps/) for this, rather than implementing it yourself?

**Comment by brarcher** [comment]
How does the syncing of an app to Dropbox work? The data for this application is stored on a sqlite database, which is assumed to be in internal storage and protected by Android's OS level permissions. Is there some mechanism for backing up an application's internal state to a 3rd party?

**Comment by brarcher** [comment]
Oh, looking at your comment on another issue, it sounds like you would like the import/export feature of the app to support encryption, right?

**Comment by betsythefc** [comment]
I'm more concerned with users accessing the app without a password or pin.

My ideal situation would be the data encrypted at rest with a password or pin for decrypting it.

I do like the idea of using openkeychain as the encryption/decryption method, that should offload the actual encryption work to another app.

**Comment by bracuphoth** [comment]
I think encryption is pointless. If not well implemented it can be easily be broken. If well implemented, it can still be broken with anything from android malware checking the memory to social engineering.

If the OP needs encryption the user should use encryption for the underlying container (disk).

Encryption would come with quite a few drawbacks.
1. Larger app meaning more memory usage and more to download
2. More things to do for the app meaning less battery life and this is not a desktop app
3. More things to fix for the author and more things that can break

If you are still contemplating this very bad idea, look at the purpose. This is an app for loyalty cards. The ones you give to the cashier to ADD loyalty points. If there is any concern regarding privacy or just protecting the data (say a credit card) something like a password safe is needed.

**Comment by betsythefc** [comment]
Fair enough. Would implementing a pin to open the app be an option, even if it doesn't encrypt?

**Comment by brarcher** [comment]
I agree with @bracuphoth regarding the encryption, using full-disk encryption would be a more suitable solution. As for protecting the application with a PIN or password, can you describe the need for it? There are a few different directions one can go with this. One can either have a PIN/password protecting the phone, in which case having additional protection on each application is redundant. If one does not have a PIN/password on the phone, is there concern that someone else will access the application inappropriately, perhaps by stealing the barcodes?

> The ones you give to the cashier to ADD loyalty points. 

There are stores which allow one to redeem points using the card, so it is only only that the barcodes are used to add points.

> If there is any concern regarding privacy or just protecting the data (say a credit card) something like a password safe is needed.

My intention with the application is that it would not be used to store information which is sensitive. I did not consider a loyalty card as sensitive. However, I am open to the idea if others believe that they are.

**Comment by betsythefc** [comment]
I would like the option for a pin/password to access it, but I have been convinced that it isn't necessary if the device itself is encrypted (which mine is).

**Comment by brarcher** [comment]
Based on the discussion, I'll close this request, as protecting the data would be better handled at the phone level instead of the individual application level.

**Comment by RoestVrijStaal** [comment]
Too bad, Loyalty Card Locker would be a good FOSS replacement of propertairy apps like Stocard :sad:

**Comment by brarcher** [comment]
@RoestVrijStaal Android has a way to lock a user to a specific app which needs a pin/etc to escape, as well as has profiles where each user (or a guest) has separate storage. Can you describe the use case where one is giving a phone to someone to borrow and wants to lock them out of certain apps but cannot use Android native setup to do so?

If one were interested in investigating this, proposing up with a solid use case where Android does not provide sufficient security mitigations as is, and submits a pull request with the necessary changes and tests, I would not be opposed to the change. Personally this use case is not relevant to my interaction with the app, so I would not be driving the feature.

> Too bad, Loyalty Card Locker would be a good FOSS replacement of propertairy [sic] apps like Stocard

Is it your stance that this feature is important enough that its absence represents a significant hurdle to adoption?
