### ISSUE TITLE
Material design icon

### ISSUE THREAD

**Issue by betsythefc** [brarcher/loyalty-card-locker#72]
I can design an icon (very similar to the one already used) that is material.

**Comment by brarcher** [comment]
Feel free to propose a new icon! (:

**Comment by brarcher** [comment]
@betsythefc Do you still have the drawing for the icon handy? To publish this application to the Google Play store I need an icon which is a 32-bit PNG (with alpha) of dimension 512 x 512 (information [here](https://support.google.com/googleplay/android-developer/answer/1078870?hl=en)). The largest icon in your contribution, under the mipmap-xxxhdpi folder, is 192 x 192. If you are able to generate a larger icon, could you post it here?

In addition, if you are up for it, the application will also need a Feature Graphic. I believe that this is the graphic displayed if the application is being featured, such as the following in the top banner on the Google Play [apps](https://play.google.com/store/apps) page:

<img width="522" alt="screen shot 2017-02-26 at 11 16 43 pm" src="https://cloud.githubusercontent.com/assets/5264535/23348598/b13c244e-fc79-11e6-84ca-778c7be1cd38.png">

This image can be a JPEG or 24-bit PNG (no alpha) with dimensions 1024 by 500. Would you be interested in also helping create this image?

Thanks!

**Comment by betsythefc** [comment]
@brarcher I have the gimp .xcf file around here somewhere I think, I'll see if I can scrounge it up again. I wouldn't mind doing the _Feature Graphic_. I'll give it a go :)

Do you have a needed time frame on this?

**Comment by brarcher** [comment]
I discovered that I needed the two images when I was attempting to publish this application to the play store. If you get around to creating the image in the next week or two I would be grateful. However, this _is_ a volunteer thing (also the app will be free), so it is really up to your availability. (:
