### ISSUE TITLE
Improve F-Droid Description

### ISSUE THREAD

**Issue by sknorr** [brarcher/loyalty-card-locker#73]
The following is not a real bug, just an issue of managing expectations...
I installed this purely out of interest and wondered how you would solve the issue that adding stamps to a phone screen does not make much sense. Because that is the most common kind of loyalty card I know - collect ten stamps on a card and get the eleventh order free.

There are other loyalty cards that are based on magnetic stripes or NFC that would not work with this app either.

I think your description on F-Droid should mention that this only works for bar code-based systems.

**Comment by brarcher** [comment]
Thanks for the feedback. Sorry that the description was misleading. I'm not too terribly good at naming things... (:

I'll update the description of the project on F-Droid to better reflect what it does.

**Comment by brarcher** [comment]
A change to the application's summary and description has been submitted:

https://gitlab.com/fdroid/fdroiddata/merge_requests/1857

If you feel that its description is still not clear or is misleading, let me know!

**Comment by brarcher** [comment]
Oh, as a note, it may take a day or so for F-Droid to update with the new description.

**Comment by sknorr** [comment]
Thanks. Looks good!
