### ISSUE TITLE
Enhancement: allow editing barcode type (and also the card number)

### ISSUE THREAD

**Issue by denilsonsa** [brarcher/loyalty-card-locker#89]
There are some stores that provide a physical card with 1D-barcode, but they also provide the same number as a QR Code in their app (IKEA is one example). Thus, I'd like to be able to change the barcode type without having to re-enter the number.

The UI can behave like this:

1. I click on the item on the app home screen.
2. I click on the `Edit` button.
3. In this screen, the *Card ID* field is disabled. I can't select (which is annoying), and I can't edit (which is also annoying). I'd like to be able to edit it in-place, without having to re-enter from scratch.
4. In the same screen, there could be another button (or a drop-down select box) that would allow me to change the barcode type. That way, I'd be able to change from 1D barcode to a QR code.

Why is this needed? Because I can scan my physical 1D card into the app, but then I can't edit it. If I want to use a different kind (QR Codes are easier to scan, specially if the phone screen is not high-res), I have to manually type the number.

**Comment by brarcher** [comment]
The application does have a way to edit the barcode. From the edit screen one would need to press the Enter Card button.

[<img src="https://cloud.githubusercontent.com/assets/5264535/18036258/bb19562e-6d33-11e6-856e-740e8785ad71.png" width=250>](https://cloud.githubusercontent.com/assets/5264535/18036258/bb19562e-6d33-11e6-856e-740e8785ad71.png)

The next screen allows one to type the desired card ID. All valid barcodes from that card ID are then generated, allowing the user to select which barcode best represents the one they are after.

[<img src="https://cloud.githubusercontent.com/assets/5264535/18036269/0202baf8-6d34-11e6-9c17-449d5b348738.png" width=250>](https://cloud.githubusercontent.com/assets/5264535/18036269/0202baf8-6d34-11e6-9c17-449d5b348738.png)

Why does the application do this? Why not let the user select the barcode type after typing in the number? At least for me I find that I do not know what the different barcode types are. If asked to pick from a dropdown I likely would pick the wrong one. Having a list of all the valid barcode types for the given card ID seemed more reasonable.

What the application currently does not do is once one clicks on the Enter Card button from the edit screen the existing barcode is not auto-populated. That is, the user must type everything from scratch. Implementing the auto-populating would be fairly simple to do. Would having the field auto-populate with the existing card ID help? Or, is your request more fundamental?

**Comment by denilsonsa** [comment]
> What the application currently does not do is once one clicks on the Enter Card button from the edit screen the existing barcode is not auto-populated. That is, the user must type everything from scratch. Implementing the auto-populating would be fairly simple to do. Would having the field auto-populate with the existing card ID help? Or, is your request more fundamental?

I think auto-populating the field is good enough, and seems to work for any use-case I can think about.

I'd do just one step further: If "card id" is empty (i.e. inserting a new card), the button should be "enter card" (just like it is now. However, if we are editing a card, the button could be renamed to "edit card". That way, it would be intuitive that we can edit the number and the type.

**Comment by brarcher** [comment]
I like your suggestion. I'll update the button text to say 'edit card' if there is already an id.

**Comment by brarcher** [comment]
The auto-populating feature has been added some time ago, and I now got around to changing the text on the "Enter card" button to "Edit card" if the card already exist.

Marking this issue as resolved. If you feel otherwise, let me know.
